### ISSUE TITLE
Nil pointer reference via quic-go

### ISSUE THREAD

**Issue by jum** [gamalan/caddy-tlsredis#47]
I could not really reproduce this, but on two of my nodes (one AMD64, one ARM Ampere), I got the following stack trace upon starting caddy and initializing the TLS certificate from Redis:

```
Aug 07 18:14:55 opc1.mager.org systemd[1]: Starting Caddy...
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: caddy.HomeDir=/var/lib/caddy
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: caddy.AppDataDir=/var/lib/caddy/.local/share/caddy
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: caddy.AppConfigDir=/var/lib/caddy/.config/caddy
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: caddy.ConfigAutosavePath=/var/lib/caddy/.config/caddy/autosave.json
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: caddy.Version=v2.7.2 h1:QqThyoyUFAv1B7A2NMeaWlz7xmgKqU49PXBX08A+6xg=
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: runtime.GOOS=linux
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: runtime.GOARCH=arm64
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: runtime.Compiler=gc
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: runtime.NumCPU=1
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: runtime.GOMAXPROCS=1
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: runtime.Version=go1.20.7
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: os.Getwd=/
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: LANG=en_US.UTF-8
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: NOTIFY_SOCKET=/run/systemd/notify
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: HOME=/var/lib/caddy
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: LOGNAME=caddy
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: USER=caddy
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: INVOCATION_ID=fb653c2b37494688ad1c8c8ed282ac30
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: JOURNAL_STREAM=8:61444618
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: {"level":"info","ts":1691432095.6437862,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: {"level":"info","ts":1691432095.7522457,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/access.log"}
Aug 07 18:14:55 opc1.mager.org caddy[2262087]: {"level":"info","ts":1691432095.784071,"caller":"caddy-tlsredis@v0.2.9/storageredis.go:278","msg":"TLS Storage are using Redis, on opc3.tail6f5c6.ts.net:6379"}
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x47b32c]
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: goroutine 136 [running]:
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(0x4000327860, {0x1a90e38, 0x4000050048}, _, _)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/caddyserver/certmagic@v0.19.1/handshake.go:378 +0xf8c
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/caddyserver/certmagic.(*Config).GetCertificateWithContext(0x4000327860, {0x1a90e38, 0x4000050048}, 0x4000327790)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/caddyserver/certmagic@v0.19.1/handshake.go:84 +0x9c4
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/caddyserver/certmagic.(*Config).GetCertificate(0x400067a2a0?, 0x4000518f30?)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/caddyserver/certmagic@v0.19.1/handshake.go:50 +0x30
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0x4000327790)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/caddyserver/caddy/v2@v2.7.2/modules/caddytls/connpolicy.go:232 +0x144
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/quic-go/qtls-go1-20.(*config).getCertificate(0x4000463500, 0x4000327790)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/common.go:1086 +0x44
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).pickCertificate(0x4000459bb0)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:415 +0x5c
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).handshake(0x4000459bb0)
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:60 +0x40
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/quic-go/qtls-go1-20.(*Conn).serverHandshake(0x400053fc00, {0x1a90e00, 0x4000579ae0})
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server.go:53 +0x138
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/quic-go/qtls-go1-20.(*Conn).handshakeContext(0x400053fc00, {0x1a90ea8, 0x40003f3380})
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1540 +0x348
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: github.com/quic-go/qtls-go1-20.(*Conn).HandshakeContext(0x0?, {0x1a90ea8?, 0x40003f3380?})
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1480 +0x24
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: created by github.com/quic-go/qtls-go1-20.(*QUICConn).Start
Aug 07 18:14:56 opc1.mager.org caddy[2262087]: 	github.com/quic-go/qtls-go1-20@v0.3.0/quic.go:179 +0xc8
Aug 07 18:14:56 opc1.mager.org systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 07 18:14:56 opc1.mager.org systemd[1]: caddy.service: Failed with result 'exit-code'.
Aug 07 18:14:56 opc1.mager.org systemd[1]: Failed to start Caddy.

```

I cannot really reproduce the problem, I have the gut feeling that it is somehow a race condition if a h3 https request comes in while caddy is still initializing the certificates. I never had it with any nodes only serving one or two domains. This one is serving about 14 domains. I had the problem once on this node and twice on another node, both serving about the same number of domains.

**Comment by francislavoie** [comment]
Please use Caddy v2.7.3, this was a problem in Caddy and not this plugin.

**Comment by jum** [comment]
Thanks for pointing that out, closing.
